use asr::settings::gui::{Gui, Title};

#[derive(Gui)]
pub struct Settings {
    pub _default_splits: Title,
    #[default = true]
    pub toggle_underworld: bool,
    #[default = true]
    pub toggle_hell_cliffs: bool,
    #[default = true]
    pub toggle_the_car_race: bool,
    #[default = true]
    pub toggle_the_whispering_vault: bool,
    #[default = true]
    pub toggle_the_subway_station: bool,
    #[default = true]
    pub toggle_the_city: bool,
    #[default = true]
    pub toggle_over_the_buildings: bool,
    #[default = true]
    pub toggle_the_warehouse: bool,
    #[default = true]
    pub toggle_the_harbor: bool,
    #[default = true]
    pub toggle_the_temple: bool,
    #[default = true]
    pub toggle_the_asian_shrine: bool,
    #[default = true]
    pub toggle_the_deities: bool,
    #[default = true]
    pub toggle_the_garden: bool,
    #[default = true]
    pub toggle_the_sun: bool,

    pub _misc_splits: Title,
    #[default = false]
    pub toggle_first_ladder: bool,
    #[default = false]
    pub toggle_hell_cliffs_drone: bool,
    #[default = false]
    pub toggle_rotating_cube: bool,
    #[default = false]
    pub toggle_open_the_door: bool,
    #[default = false]
    pub toggle_the_aqua_maze: bool,
    #[default = false]
    pub toggle_station_drone: bool,
    #[default = false]
    pub toggle_red_elevator_to_city: bool,
    #[default = false]
    pub toggle_city_crane: bool,
    #[default = false]
    pub toggle_double_crane_platforms: bool,
    #[default = false]
    pub toggle_elevator_to_buildings: bool,
    #[default = false]
    pub toggle_buildings_helicopter: bool,
    #[default = false]
    pub toggle_blue_railing_chariot: bool,
    #[default = false]
    pub toggle_elevator_to_stairs: bool,
    #[default = false]
    pub toggle_helicopter_to_temple: bool,
    #[default = false]
    pub toggle_elevator_to_asian_shrine: bool,
    #[default = false]
    pub toggle_wooden_horse_wagon: bool,
    #[default = false]
    pub toggle_wooden_boat: bool,
    #[default = false]
    pub toggle_zeus_lightning: bool,
    #[default = false]
    pub toggle_air_balloon_pump: bool,
    #[default = false]
    pub toggle_the_final_trials: bool,
    #[default = false]
    pub toggle_kiosk: bool,
    #[default = false]
    pub toggle_carriage: bool,
}
